# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39ef550e14ba7fb562b8b5b695986d6c1622ed7c779f0491a10ac34c3c510142073ba762749f566a471e5fae59ea2446e0858a2e4a98f56e3dfce7befb5c0cf7

test:
  secret_key_base: 9c8203227b51ea317e9ccdd0d81ace08dfed73970f860b339d12d2400e12c05cbd37fba2c467b007c6e5f02f02b55b66316ec4817a41cf3881c13618a1c98a0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
